name: GitHub Actions
on: [pull_request, push]
env:
  DATABASE_URL: postgres://atpmgikgxrslyi:dad32713d59e128602908fa0c2435be8ff7a08f0666bb3fbe70ae2c1a188c3ee@ec2-50-19-32-96.compute-1.amazonaws.com:5432/df22photd233tb?schema=test
jobs:
  testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['16']
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm -g install yarn
      - run: yarn
      - run: yarn lint
      - run: yarn test